
languageCode = "en-in"
title = "Rutansh"
theme = "bearblog"
publishDir = "docs"
author = "Rutansh"
copyright = "Rutansh"

[params]
  description = "A weekly archive of thought, responsibility, and national conscience."
  hideMadeWithLine = true
