baseURL = "https://rutansh.in/"
languageCode = "en-in"
title = "Rutansh"
theme = "bearblog"

author = "Rutansh"
copyright = "Rutansh"

[params]
  description = "A weekly archive of thought, responsibility, and national conscience."
  hideMadeWithLine = true
