baseURL = "https://rutansh.in/"
languageCode = "en-in"
title = "Rutansh"
theme = "bearblog"

enableRobotsTXT = true

[params]
googleAnalytics = "G-C39PCJ09B4"
description = "A weekly archive of thought, responsibility, and national conscience."
hideMadeWithLine = true

